spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-version: 0
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration